### ISSUE TITLE
Does't work well

### ISSUE THREAD

**Issue by Rashfu** [laffernandes/kht#1]
Grateful for your work.
But I seem to meet with some problems in lane detection by using your kht algorithm.
Here is the binary image
![image](https://user-images.githubusercontent.com/42403175/79106017-49884f80-7da4-11ea-8a2e-e29112f9a177.png)
But the result is so confusing.There are too many false line.
![image](https://user-images.githubusercontent.com/42403175/79106127-7b011b00-7da4-11ea-83ca-e75a0733ad05.png)

**Comment by laffernandes** [comment]
Dear Rashuf,

Could you please send me the original RGB and edge images that you are using? I need to take a close look to identify what could be causing the problem.

You can send them to laffernandes@ic.uff.br

Best regards,
Leandro

**Comment by Rashfu** [comment]
> Dear Rashuf,
> 
> Could you please send me the original RGB and edge images that you are using? I need to take a close look to identify what could be causing the problem.
> 
> You can send them to [laffernandes@ic.uff.br](mailto:laffernandes@ic.uff.br)
> 
> Best regards,
> Leandro



> Dear Rashuf,
> 
> Could you please send me the original RGB and edge images that you are using? I need to take a close look to identify what could be causing the problem.
> 
> You can send them to [laffernandes@ic.uff.br](mailto:laffernandes@ic.uff.br)
> 
> Best regards,
> Leandro

Dear Leandro,

Thank you for your time. 
I have send two original images. Lane detection is the final result I want to get. I try to change the cluster_min_size parameter of the run_kht funtion to 20 and the result is like this:
![1](https://user-images.githubusercontent.com/42403175/79222257-ce00ce00-7e89-11ea-932c-22935cee054e.PNG)
Some detected lines from bottom-left to top-right are clearly false.I wanna figure out the reason

**Comment by laffernandes** [comment]
Dear Rashuf,

I received the image files sent by you. There are some critical points to remember when working with a Hough Transform (HT). One of them is that the number of lines to be considered is a parameter to be informed. In KHT, the amount of spurious lines is usually less than in other HTs. This means that of the lines returned by the transform, it is necessary to consider only the first T, where T is a value defined by the user/application.

In the example below, I drew only the 30 most relevant lines found. If I drew all the 176 detected lines, there would be a lot of spurious detections. For all lines draw you will find a clear collinear sequence of edge pixels supporting it. This includes the hood of the car, even if this is not of interest to your application.

![untitled3](https://user-images.githubusercontent.com/9990407/79230196-9ae31e00-7e3a-11ea-9fca-557aa2cfd7a3.png)
![untitled2](https://user-images.githubusercontent.com/9990407/79230210-9e76a500-7e3a-11ea-830e-d40c50255cb7.png)
![untitled1](https://user-images.githubusercontent.com/9990407/79230215-a0406880-7e3a-11ea-924e-04cdcd235229.png)

Another point is that the quality of the detected lines is directly related to the quality of the edge image given as input to the HT.  In the image below, the dashed line between the lanes is blurred, so that the Canny edge detection does not return adequate collinear edges pixels for then. As a result, KHT is unable to detect relevant support lines among the T = 30 lines draw.

![untitled4](https://user-images.githubusercontent.com/9990407/79230914-af73e600-7e3b-11ea-88bc-8f1f93631179.png)
